### ISSUE TITLE
Make selfplay pong work

### ISSUE THREAD

**Issue by cloderic** [cogment/cogment-verse#150]
**Goal**
Train an AI agent using PPO with replay buffer to achieve good performance on the Pong game in the Petting Zoo environment

**Acceptance Criteria**
- [ ] Trained AI agent is able to play Pong game effectively, achieving an averaged score higher than [3000 steps](https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/Pettingzoo-s-Multi-agent-Atari-CleanRL-s-PPO--VmlldzoyMDkxNTE5)
- [ ] PPO algorithm is successfully integrated into the cogment-verse training pipeline
- [ ] Write a detailed README file that includes instructions on how to run the code and how to reproduce the results

**Comment by lhnguyen102** [comment]
@cloderic I don't think the following code in the sample producer represents the terminal condition of the environment i.e. `done`
```python
done = sample.trial_state == cogment.TrialState.ENDED
```
The environment and sample producer can run asynchronously, potentially ending trials before all samples are collected. In an experiment with Pong games, I manually set the terminal condition to end after 11 steps, but the sample producer reported the environment had ended after only 3 steps due to that line of code. This caused incorrect results, as all computations involving the environment's terminal conditions were needed for PPO with replay buffer
What do you think?

**Comment by lhnguyen102** [comment]
Yes, I do. I manually set the final observation to zeros when the environment ends. However, it did not provide this final observation in the sample producer when `done` is `true`. FYI: I only ran with a single trial for this test in order to debug the issue. I will investigate further on this issue

**Comment by cloderic** [comment]
The way it should work is described here -> https://cogment.ai/docs/guide/development-guide#trial-end

**Comment by LailaElMoujtahid** [comment]
@ha --> performance not good yet + coordinate with @wduguay-air
